<?xml version="1.0" encoding="UTF-8"?><testrun name="CalculatorProjectTest" project="JunitProjectTest" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="io.cal.CalculatorProjectTest" time="0.074" displayname="CalculatorProjectTest" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]">
    <testcase name="areaofcircle" classname="io.cal.CalculatorProjectTest" time="0.074" displayname="areaofcircle()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:areaofcircle()]">
      <failure>
        <expected>314.159265358979</expected>
        <actual>314.1592653589793</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;314.159265358979&gt; but was: &lt;314.1592653589793&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:70)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:65)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:889)&#13;
	at io.cal.CalculatorProjectTest.areaofcircle(CalculatorProjectTest.java:51)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
